# This is a basic workflow to help you get started with Actions

name: Test

defaults:
  run:
    shell: bash
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev, ci ]
  pull_request:
    branches: [ master, dev, ci ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # Runs on all major platforms 
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        agda: ["lts-20.26 Agda-2.6.4"]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # actions:

      - name: ⏬ Setup Haskell environment
        id: haskell-setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2.8'
          stack-version: latest
          cabal-update: false
          enable-stack: true

      - name: 🔍 Setting variables (Unix)
        if: runner.os != 'Windows'
        run: | 
          echo "STACK_LOCAL_BIN=$(stack path --local-bin)" >> "$GITHUB_ENV"
          echo "STACK_ROOT_CORRECT=${{ steps.haskell-setup.outputs.stack-root }}" >> "$GITHUB_ENV"

      - name: 🔍 Setting variables (Windows)
        if: runner.os == 'Windows'
        run: | 
          echo "STACK_LOCAL_BIN=$(stack path --local-bin)" >> "$GITHUB_ENV"
          echo "STACK_ROOT_CORRECT=C:/Users/runneradmin/AppData/Roaming/stack" >> "$GITHUB_ENV"

      - name: 🔍 Reviewing variables
        run: |
          echo "runner.os         = ${{ runner.os                               }}"
          echo "ghc-path          = ${{ steps.haskell-setup.outputs.ghc-path    }}"
          echo "ghc-exe           = ${{ steps.haskell-setup.outputs.ghc-exe     }}"
          echo "stack-path        = ${{ steps.haskell-setup.outputs.stack-path  }}"
          echo "stack-exe         = ${{ steps.haskell-setup.outputs.stack-exe   }}"
          echo "stack-root        = ${{ steps.haskell-setup.outputs.stack-root  }}"
          echo "STACK_ROOT_CORRECT = $STACK_ROOT_CORRECT"
          echo "STACK_LOCAL_BIN    = $STACK_LOCAL_BIN"
    
      # cached stuff to be restored:
      - name: 💾 Restore cached stack global package db
        id:   stack-global
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.STACK_ROOT_CORRECT }}
          key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}
          restore-keys: |
              ${{ runner.os }}-stack-global

      - name: 💾 Restore stack-installed binaries in ~/.local/bin
        id:   stack-binaries
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.STACK_LOCAL_BIN  }}
          key: ${{ runner.os }}-stack-binaries-${{ hashFiles('**.yaml') }}
          restore-keys: |
              ${{ runner.os }}-stack-binaries
        
      - name: ⏬ Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 🛠️ Add Stack install directory to PATH (Windows)
        if : runner.os == 'Windows'
        run: |
          echo "$APPDATA/local/bin" >> $GITHUB_PATH

      - name: 🛠️ Add Stack install directory to PATH (Unix)
        if : runner.os != 'Windows'
        run: PATH=$(stack path --local-bin):$PATH
      
      - name: ⏬ Install Agda
        run: |
          stack install --resolver ${{ matrix.agda }}
          which agda
          agda --version

      # things to be cached

      - name: 💾 Cache stack global package db
        if:   always() && steps.stack-global.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.STACK_ROOT_CORRECT }}
          key: ${{ steps.stack-global.outputs.cache-primary-key }}

      - name: 💾 Cache stack-installed binaries
        if:   always() && steps.stack-binaries.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.STACK_LOCAL_BIN }}
          key: ${{ steps.stack-binaries.outputs.cache-primary-key }}
    
      - name: ⏬ Install NPM Dependencies
        run: npm install
        
      - name: 🔨 Build stuff 
        run: npm run build

      - name: 🚗 Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: 🚗 Run tests (Windows, MacOS)
        if: runner.os != 'Linux'
        run: npm test 
